# Site settings
title: CodeSha.me
email: caleyjack@me.com
description: "Shaming developers one iteration at a time since 2014"
baseurl: ""
url: "http://codesha.me"
twitter_username: caleyjack
github_username:  robojack

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty

# Pagination
paginate: 10
paginate_path: "page/:num"

exclude:
  - '*.haml'
  - 'bower_components'
  - 'node_modules'
  - '*.rb'
  - '*.coffee'
  - 'Guardfile'
  - 'Procfile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.yml'
  - 'app'
  - 'bower.json'
  - 'package.json'
  - 'Gruntfile.coffee'
  - '.fontcustom-manifest.json'
  - 'Readme.md'


defaults:
  values:
    layout: "default"
